name: flet_notifications
description: Flet Notifications control
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet-notifications/src/flutter/flet_notifications
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  awesome_notifications: ^0.10.0

  flet:
    path: ../flet




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0